### ISSUE TITLE
how to add function 

### ISSUE THREAD

**Issue by DeXteR25** [DeXteR25/OrderSys#10]
<div className="rowPad">
                                        <button className="btn  btn-lg" onclick="getData('Mo:Mo')" >Mo:Mo</button>
                                        <button className="btn  btn-lg" onclick="getData('Chowmin')">Chowmin</button>
                                        <button className="btn  btn-lg" onclick="getData('Burger')">Burger</button>
                                        <button className="btn  btn-lg" onclick="getData('Cola')">Cola</button>
                                        <button className="btn  btn-lg" onclick="getData('pepsi')">Pepsi</button>
                                    </div>

**Comment by DeXteR25** [comment]
when button click I can be able to go to target page but there is nothing on that page

**Comment by Gitsanto** [comment]
send me screenshot

**Comment by DeXteR25** [comment]
Done
